openapi: 3.0.0
info:
  title: HireLoop API
  version: 0.1.0
paths:
  /jobs/create:
    post:
      summary: Create a job from JD text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jdText:
                  type: string
              required:
                - jdText
      responses:
        '200':
          description: Created job
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  publicUrl:
                    type: string
